### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by fintzij** [fintzij/MultistateModels.jl#19]
- [x] Initializers for model parameters
- [x] Splines for baseline hazards
- [x] Fix ISplines for baseline intensities - constrain all parameters to be the same sign, currently constrained to all be positive
- [x] Upweight redundant paths so likelihood is not evaluated
- [x] in MCEM, simulate additional paths only for subjects with low ESS
- [x] Object type for fitted semi-Markov process
- [x] Likelihoods for mixed exact + panel data
- [x] Benchmark against MSM
- [x] Test MCEM marginal variance-covariance matrix
- [ ] Penalized splines using DataInterpolations.jl to replace BSplineKit.jl
- [ ] user supplied transition intensities
- [ ] fix bug in cumulative incidence function when statefrom is specified and add annotation for output for both signatures
- [ ] clarify cumulative incidence function is for each transition, not the process. should have both
- [ ] improved parameter handing via https://github.com/JuliaGaussianProcesses/ParameterHandling.jl
- [ ] Log-likelihoods taking subject weights as parameters instead of model pars (facilitate IJ, etc.)
- [ ] Splines for covariates + penalized splines for covariates and baseline hazards
- [ ] Aalen-Johansen
- [ ] optimization problem now allows for data loader: https://juliaml.github.io/MLUtils.jl/stable/api/#MLUtils.DataLoader
- [ ] replace joint optimization with optimization of each hazard separately - can be accomplished via color matrix passed on to Optimization.jl
- [ ] infinitesimal jackknife estimate for the variance + cross-validation/model comparison
- [ ] make non-modifying versions of initialize_parameters! and set_parameters!
- [ ] in simulation function, add tmax argument that overrides the maximum observation time

**Comment by fintzij** [comment]
likelihoods with subj weights as parameters
